name: user_repository
description: Dart package which manages the user repository from firestore
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  authentication_repository:
    path: ../authentication_repository
  equatable: ^2.0.3
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  cloud_firestore: ^3.4.9
  

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter