name: firestore_repository
description: Dart package which manages the cloud firestore.
version: 1.0.0
publish_to: none,

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.9
