// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG_fkcj9O6cj5swwTy-XI1S_k00u3kFio',
    appId: '1:459638878844:web:758a3a1ed37ea728a90ff9',
    messagingSenderId: '459638878844',
    projectId: 'anfari-44444',
    authDomain: 'anfari-44444.firebaseapp.com',
    storageBucket: 'anfari-44444.appspot.com',
    measurementId: 'G-4YX3E2D4MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJPAo-IIAQQh1VxS1e5rMpUe2NZmuMBpU',
    appId: '1:459638878844:android:20cf9fd58d0af9f7a90ff9',
    messagingSenderId: '459638878844',
    projectId: 'anfari-44444',
    storageBucket: 'anfari-44444.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUCWVfTbL4LkrXyJWBcZUkNzaXmOqQPaQ',
    appId: '1:459638878844:ios:310f75bf1159ca35a90ff9',
    messagingSenderId: '459638878844',
    projectId: 'anfari-44444',
    storageBucket: 'anfari-44444.appspot.com',
    iosClientId: '459638878844-k3vf0j89bi9qhktdcipjmilvkd5bsqv5.apps.googleusercontent.com',
    iosBundleId: 'dz.goudjal.anfari',
  );
}
