// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMJGItlpx9IUt5fCfZlSOcEaF0_sLT2CM',
    appId: '1:311115419598:web:4d6e46fbf70da833ede59f',
    messagingSenderId: '311115419598',
    projectId: 'anfari-5665e',
    authDomain: 'anfari-5665e.firebaseapp.com',
    storageBucket: 'anfari-5665e.appspot.com',
    measurementId: 'G-KTFVV4P85C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpLS0KrkR8130crgR3sKecjQoRAR2yutc',
    appId: '1:311115419598:android:b57b804b8b46caf1ede59f',
    messagingSenderId: '311115419598',
    projectId: 'anfari-5665e',
    storageBucket: 'anfari-5665e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvcvsMsJNquozE-nTUzgZkm_qJrixVSMA',
    appId: '1:311115419598:ios:c989cd7a7c0932adede59f',
    messagingSenderId: '311115419598',
    projectId: 'anfari-5665e',
    storageBucket: 'anfari-5665e.appspot.com',
    iosClientId: '311115419598-6vm1e4v9ooo24uj73nko8o4519a2niio.apps.googleusercontent.com',
    iosBundleId: 'dz.goudjal.anfari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvcvsMsJNquozE-nTUzgZkm_qJrixVSMA',
    appId: '1:311115419598:ios:c989cd7a7c0932adede59f',
    messagingSenderId: '311115419598',
    projectId: 'anfari-5665e',
    storageBucket: 'anfari-5665e.appspot.com',
    iosClientId: '311115419598-6vm1e4v9ooo24uj73nko8o4519a2niio.apps.googleusercontent.com',
    iosBundleId: 'dz.goudjal.anfari',
  );
}
