name: storage_repository
description: Dart package which manages the storage domain.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  firebase_storage: ^10.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter